project_id = "ikrivrudkvvnksollslh"

[functions.market-data]
verify_jwt = false

[functions.realtime-prices]
verify_jwt = false

[functions.realtime-market-data]
verify_jwt = false

[functions.calculate-trend]
verify_jwt = false

[functions.position-rebalancer]
verify_jwt = false
