// ============= StochRSI / oscillator category view (Phase 3B) =============
export {
  STOCHRSI_THRESHOLDS,
  DEEP_STOCHRSI_HARD_GATE,
  PRE_MOMENTUM_STOCHRSI_PARAMS,
  STOCHRSI_DECLINE_BONUS_PARAMS,
  STOCHRSI_ADX_ALIGNMENT_PARAMS,
  STOCHRSI_DYNAMIC_PARAMS,
  STOCHRSI_RUNWAY_GATE,
  DYNAMIC_ENTRY_WINDOW,
  RSI_THRESHOLDS,
  RSI_ZONE_THRESHOLDS,
  NEAR_EXTREME_PROTECTION_GATE,
  TIME_IN_EXTREME_PARAMS,
} from "../constants.ts";
