// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-open-positions.ts
import { createClient } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_open_positions_default = defineTool({
  name: "list_open_positions",
  title: "List open positions",
  description: "List the signed-in user's currently open trading positions with entry price, side, quantity, unrealized PnL, stop-loss, and take-profit.",
  inputSchema: {
    symbol: z.string().trim().optional().describe("Optional symbol filter, e.g. BTCUSDT."),
    limit: z.number().int().min(1).max(100).default(25).describe(
      "Maximum number of positions to return (default 25)."
    )
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ symbol, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let q = sb.from("positions").select(
      "id, symbol, side, status, quantity, entry_price, current_price, stop_loss, take_profit, realized_pnl_percent, peak_pnl_percent, strategy_name, opened_at"
    ).eq("status", "open").order("opened_at", { ascending: false }).limit(limit);
    if (symbol) q = q.eq("symbol", symbol.toUpperCase());
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { positions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-recent-closed-positions.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_recent_closed_positions_default = defineTool2({
  name: "list_recent_closed_positions",
  title: "List recent closed positions",
  description: "List the signed-in user's most recently closed trading positions with realized PnL, close reason, and strategy.",
  inputSchema: {
    symbol: z2.string().trim().optional().describe("Optional symbol filter, e.g. ETHUSDT."),
    limit: z2.number().int().min(1).max(200).default(25).describe(
      "Maximum number of closed positions to return (default 25)."
    )
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ symbol, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    let q = sb.from("positions").select(
      "id, symbol, side, quantity, entry_price, exit_price, realized_pnl, realized_pnl_percent, close_reason, strategy_name, opened_at, closed_at"
    ).eq("status", "closed").order("closed_at", { ascending: false }).limit(limit);
    if (symbol) q = q.eq("symbol", symbol.toUpperCase());
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { positions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-recent-signals.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_recent_signals_default = defineTool3({
  name: "list_recent_signals",
  title: "List recent trading signals",
  description: "List the signed-in user's most recent trading signals with symbol, side, entry price, SL/TP, confidence, and strategy.",
  inputSchema: {
    symbol: z3.string().trim().optional().describe("Optional symbol filter."),
    status: z3.enum(["active", "executed", "expired", "rejected"]).optional().describe("Optional status filter."),
    limit: z3.number().int().min(1).max(200).default(25).describe(
      "Maximum number of signals to return (default 25)."
    )
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ symbol, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    let q = sb.from("trading_signals").select(
      "id, symbol, signal_type, entry_price, stop_loss, take_profit, confidence_score, risk_reward_ratio, strategy_name, status, trend, reason, created_at, executed_at, expires_at"
    ).order("created_at", { ascending: false }).limit(limit);
    if (symbol) q = q.eq("symbol", symbol.toUpperCase());
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { signals: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-portfolio-summary.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_portfolio_summary_default = defineTool4({
  name: "get_portfolio_summary",
  title: "Get portfolio summary",
  description: "Return an aggregate snapshot for the signed-in user: open position count, total open notional, and realized PnL over the last 24h / 7d / 30d.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    const { data: openRows, error: openErr } = await sb.from("positions").select("quantity, entry_price, current_price, side").eq("status", "open");
    if (openErr) {
      return { content: [{ type: "text", text: openErr.message }], isError: true };
    }
    const openCount = openRows?.length ?? 0;
    let openNotional = 0;
    let unrealizedPnl = 0;
    for (const p of openRows ?? []) {
      const px = Number(p.current_price ?? p.entry_price ?? 0);
      const qty = Number(p.quantity ?? 0);
      openNotional += Math.abs(qty * px);
      const entry = Number(p.entry_price ?? 0);
      const sign = (p.side ?? "").toUpperCase() === "SHORT" ? -1 : 1;
      unrealizedPnl += sign * (px - entry) * qty;
    }
    const now = Date.now();
    const windows = {
      last_24h: now - 24 * 60 * 60 * 1e3,
      last_7d: now - 7 * 24 * 60 * 60 * 1e3,
      last_30d: now - 30 * 24 * 60 * 60 * 1e3
    };
    const realized = {};
    for (const [label, since] of Object.entries(windows)) {
      const { data, error } = await sb.from("positions").select("realized_pnl").eq("status", "closed").gte("closed_at", new Date(since).toISOString());
      if (error) {
        return { content: [{ type: "text", text: error.message }], isError: true };
      }
      const trades = data?.length ?? 0;
      const pnl = (data ?? []).reduce((acc, r) => acc + Number(r.realized_pnl ?? 0), 0);
      const wins = (data ?? []).filter((r) => Number(r.realized_pnl ?? 0) > 0).length;
      realized[label] = { trades, pnl: Number(pnl.toFixed(2)), wins };
    }
    const summary = {
      open_positions: openCount,
      open_notional_usd: Number(openNotional.toFixed(2)),
      unrealized_pnl_usd: Number(unrealizedPnl.toFixed(2)),
      realized
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ikrivrudkvvnksollslh";
var mcp_default = defineMcp({
  name: "daily-trading-bot-mcp",
  title: "Daily Trading Bot",
  version: "0.1.0",
  instructions: "Read-only access to the signed-in user's algorithmic trading account: open positions, recently closed trades, generated signals, and portfolio summary. All calls run under the user's Supabase session and respect row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_open_positions_default,
    list_recent_closed_positions_default,
    list_recent_signals_default,
    get_portfolio_summary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
