
-- Create default risk_parameters for existing user who doesn't have one
-- This is a one-time fix for the data integrity issue
INSERT INTO risk_parameters (
  user_id,
  portfolio_value,
  max_open_trades,
  max_risk_per_trade_percent,
  max_trades_per_symbol,
  daily_loss_limit_percent,
  consecutive_loss_threshold,
  position_size_reduction_percent,
  min_confidence_threshold,
  min_trend_consistency,
  is_trading_enabled,
  paper_trading_mode,
  auto_execute_signals,
  email_notifications_enabled,
  sms_notifications_enabled,
  trailing_stop_enabled,
  trailing_stop_activation_percent,
  trailing_stop_distance_multiplier,
  auto_rebalance_enabled,
  rebalance_loss_threshold_percent,
  max_positions_to_close_per_cycle,
  enable_pullback_signals,
  pullback_position_size_percent,
  enable_early_reversal_signals,
  early_reversal_position_size_percent,
  standard_tp_multiplier,
  divergence_tp_multiplier,
  divergence_sl_multiplier,
  current_open_trades,
  consecutive_losses,
  daily_realized_loss,
  last_loss_reset_date
)
SELECT 
  id,
  10000,
  5,
  1.5,
  1,
  5.0,
  3,
  50,
  60,
  50,
  true,
  true,
  true,
  true,
  true,
  true,
  1.0,
  1.5,
  false,
  1.0,
  3,
  true,
  50,
  true,
  40,
  2.5,
  2.0,
  0.67,
  0,
  0,
  0,
  CURRENT_DATE
FROM auth.users
WHERE NOT EXISTS (
  SELECT 1 FROM risk_parameters WHERE user_id = auth.users.id
);
